language: scala
sudo: false
scala:
  - 2.12.6
jdk:
  - oraclejdk8
before_install:
  - export PATH=${PATH}:./vendor/bundle
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck test
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt publish; fi
